### ISSUE TITLE
After Update to 1.18.0 | java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_17_R1/CraftWorld

### ISSUE THREAD

**Issue by tininet** [Badading/The_Gate#9]
It seems, that this plugin tries to access pre 1.18 API 

Console Output:

Could not pass event PlayerMoveEvent to The_Gate v0.1.12mc1.17.1

`at thegate.gate.packages.PackageManager.CreateArmorStand(PackageManager.java:29) ~[The_Gate0.1.12mc1.17.1.jar:?]
at thegate.gate.CreateGate.CreateGateRing(CreateGate.java:46) ~[The_Gate0.1.12mc1.17.1.jar:?]
at thegate.gate.GateObject.Repair(GateObject.java:151) ~[The_Gate0.1.12mc1.17.1.jar:?]
at thegate.gate.GateObject.Display(GateObject.java:170) ~[The_Gate0.1.12mc1.17.1.jar:?]
at thegate.gate.GateObject.addPlayerInRange(GateObject.java:306) ~[The_Gate0.1.12mc1.17.1.jar:?]
at thegate.gate.GateManager.GateInRadius(GateManager.java:95) ~[The_Gate0.1.12mc1.17.1.jar:?]
at thegate.main.TheGateMain.OnPlayerMove(TheGateMain.java:398) ~[The_Gate0.1.12mc1.17.1.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor21.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:git-Paper-39]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.18-R0.1-SNAPSHOT.jar:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleMovePlayer(ServerGamePacketListenerImpl.java:1436) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket.handle(ServerboundMovePlayerPacket.java:114) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundMovePlayerPacket$Pos.handle(ServerboundMovePlayerPacket.java:42) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1413) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1391) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1384) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:110) ~[?:?]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1518) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.jar:git-Paper-39]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.jar:git-Paper-39]
at java.lang.Thread.run(Thread.java:833) ~[?:?]`

Server ist running on Paper version git-Paper-52 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: a50e273)

**Also using:**
LuckPerms
WorldEdit
SkipNight
PlaceholderAPI
DiscordSRV

**Comment by EndMy5uffering** [comment]
this error should be fixed with the new updated plugin version for 1.18.1 you can download it [here](https://www.spigotmc.org/resources/the-gate.70247/)

**Comment by tininet** [comment]
It is fixed. Thank you.
